// Mocks generated by Mockito 5.4.4 from annotations
// in mottu_marvel/test/app/data/datasources/character_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mottu_marvel/app/core/api/cache_service.dart' as _i2;
import 'package:mottu_marvel/app/core/api/character_response_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i2.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic isExists({required String? boxName}) =>
      super.noSuchMethod(Invocation.method(
        #isExists,
        [],
        {#boxName: boxName},
      ));

  @override
  dynamic addData(_i3.CharacterResponseModel? response) =>
      super.noSuchMethod(Invocation.method(
        #addData,
        [response],
      ));

  @override
  _i4.Future<void> deleteAllData() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
